### ISSUE TITLE
[Melhoria] Single quotes 

### ISSUE THREAD

**Issue by caiobsouza** [jonathasbsouza/webdeveloperbootcamp#2]
https://github.com/jonathasbsouza/webdeveloperbootcamp/blob/63b0d37ccc8178b7edbaf81cd4f9bb4d2ebd417c/3_javascript/array%20problem%20set/arrayproblem.js#L1

Single quotes, sempre. Não é obrigatório ou errado, mas a maioria dos projetos hoje utiliza single-quotes em strings. Uma boa é tu usar um [linter](https://eslint.org/) no teu código

**Comment by jonathasbsouza** [comment]
Ajustado porém nao consegui configurar o eslint. Vou tentar na próxima.
