### ISSUE TITLE
[Melhoria] Uso do .reduce()

### ISSUE THREAD

**Issue by caiobsouza** [jonathasbsouza/webdeveloperbootcamp#3]
https://github.com/jonathasbsouza/webdeveloperbootcamp/blob/63b0d37ccc8178b7edbaf81cd4f9bb4d2ebd417c/3_javascript/array%20problem%20set/arrayproblem.js#L30

Eu estou ligado que a ideia desse exercício é te mostrar essas técnicas de controle de fluxo de programa `for`, `if`, etc. Mas depois tu pode tentar resolver isso com `.reduce(...)` também.

**Comment by jonathasbsouza** [comment]
Não consegui fazer. Pelo q tinha entendido do `.reduce`, o meu código ficaria assim:

`function max(array) {
  let maxnumber = array.reduce(function(fst, sec) {
    if(sec > fst) {
    let maxnumber = sec;
    }
  });
  console.log(maxnumber)
}`

mas não funciona.

**Comment by jonathasbsouza** [comment]
ajustado.
sintaxe reduce + if
`array.reduce((accumulator, currentValue) => (ifstatement) ? valorSeVerdade : valorSeFalso);`
